### ISSUE TITLE
Auto grind doesnt work

### ISSUE THREAD

**Issue by Kubk0** [vojta-dev/wocabee-bot#1]
it fails to translate any text 
![image](https://user-images.githubusercontent.com/67911221/135462612-431dea22-68b5-4a66-8c07-dbf53a738416.png)

**Comment by Kubk0** [comment]
doesnt work for chrome or edge either

**Comment by vojta-dev** [comment]
The auto grind only works when the switch at the bottom is at "2 WocaPoints". Does that fix the problem?

**Comment by Kubk0** [comment]
no it doesnt

**Comment by vojta-dev** [comment]
Well, I have no idea then, because it works for me... Maybe try it in the incognito mode? Or if you want to, send a video? I wasn't able to replicate this problem...

**Comment by Kubk0** [comment]
tried in incognito now it does it works but sometimes every ~5 words it skips and misses out on the bonuses

https://user-images.githubusercontent.com/67911221/135630026-1d6376f2-3534-4cff-a937-79dc02a04744.mp4

**Comment by Kubk0** [comment]
and on some packs the previous error still happens

https://user-images.githubusercontent.com/67911221/135631226-a463ae43-f20c-4ff8-8c6c-c5bbd46f5853.mp4

**Comment by vojta-dev** [comment]
Thanks a lot for the videos! I can see the problem now, and it's that I didn't know that there aren't only time-based tasks, but there are also tasks without the time limit, I don't know why do the tasks without time limit appear tho. Because for me, I couldn't find a way to get those (tested right now)

**Comment by vojta-dev** [comment]
Alright, I have maybe fixed it? I can't really test out if it works, so give it a shot if you want to. https://pastebin.com/wXnBA3pH

**Comment by Kubk0** [comment]
it works now
