### ISSUE TITLE
auto-save

### ISSUE THREAD

**Issue by Kubk0** [vojta-dev/wocabee-bot#3]
is it possible for the bot to click the save button and then continue with a user specified pack like a variable or text input box?

**Comment by Kubk0** [comment]
i dont think its able to click so i guess no

**Comment by voytxt** [comment]
It is possible, but I don't see how it's useful...

**Comment by Kubk0** [comment]
When the bot is running the computer or internet browser can crash this happened to me quita a lot of Times so an auto save would be useful
