### ISSUE TITLE
detekované

### ISSUE THREAD

**Issue by ghost** [vojta-dev/wocabee-bot#5]
je to detekované, dá ti to iba warn ak to použiješ znova, tak to upozorni učiteľku/učiteľa a zmaže ti to učet :)

**Comment by voytxt** [comment]
Už jsem si toho taky všiml, uvidím co s tím...

**Comment by voytxt** [comment]
Hmm, jejich detekce je primitivní, prostě se podívají každou sekundu jestli je na stránce element s id "wocaBot", pokud ano, tak ukážou strašidelnou zprávu a pošlou serveru že podvádíš. Samozřejmě bych tam mohl dát náhodné id a tak, ale myslím že za chvilku už by mohli začít lidi banovat, nebo upozorňovat učitele, což vážně nechci. Takže jak to tak vidím, archivnu tohle repo a přidám varovnou zprávu do README a na stránku. Kdokoliv kdo chce ať si ho klidně forkne a udělá lepší verzi WocaBotu, ale já už pravděpodobně na tomhle projektu pracovat nebudu.
